### PR TITLE
Add severity to issue output

### PR DESCRIPTION
**Pull request by GordonDiggs**
The spec requires these to be one of info, normal, or critical

@codeclimate/review

### CODE REVIEW

**Comment by GordonDiggs** [comment]
@pbrisbin fixed your comment!

**Comment by pbrisbin** [comment]
Did you intend to remove `#severity` or are you arguing it should stay?

**Comment by GordonDiggs** [comment]
@pbrisbin what do you mean? I didn't remove anything

**Comment by pbrisbin** [comment]
I had a comment that the `#severity` method is low-value (IMO) and could be inlined.

You said you *fixed my comment*.

The method it still there, so I'm asking if you were implicitly saying you preferred to keep it, or you meant to remove it but forgot.

Does that make sense?

**Comment by GordonDiggs** [comment]
@pbrisbin ah sorry - I didn't see that comment. I was referring to the comment about rebasing. I agree about inlining it - just pushed that up

**Comment by pbrisbin** [comment]
LGTM -- I might consider using `#fetch`, but no biggie either way.

**Pull request merged**
